apiVersion: v1
kind: Service
metadata:
  name: {{SVC_NAME}}
  labels:
    app: {{APP_NAME}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_NAME}}
  ports:
    - name: queue-port
      port: 5672
    - name: cluster-port
      port: 4369
    - name: dist-port
      port: 25672
      
